"""Your migration message

Revision ID: 94b3cc1dc939
Revises: 6811dc464778
Create Date: 2024-09-10 17:05:50.115993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94b3cc1dc939'
down_revision = '6811dc464778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geophysical', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archival_excel', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('archival_pdf', sa.String(length=255), nullable=True))
        batch_op.drop_column('archival_material')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geophysical', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archival_material', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('archival_pdf')
        batch_op.drop_column('archival_excel')

    # ### end Alembic commands ###
