"""empty message

Revision ID: 0dfe676f8a13
Revises: f0e2b7196218
Create Date: 2025-02-06 06:42:02.422210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dfe676f8a13'
down_revision = 'f0e2b7196218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geophysic_seismic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_type', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geophysic_seismic', schema=None) as batch_op:
        batch_op.drop_column('profile_type')

    # ### end Alembic commands ###
