"""added last email sent

Revision ID: 513bfada0e26
Revises: 0dfe676f8a13
Create Date: 2025-04-15 12:57:13.328205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513bfada0e26'
down_revision = '0dfe676f8a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_sent_email', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_sent_email')

    # ### end Alembic commands ###
