"""Initial migration

Revision ID: 6811dc464778
Revises: fad975a3db37
Create Date: 2024-09-06 16:26:10.286277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6811dc464778'
down_revision = 'fad975a3db37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_geophysic', sa.Boolean(), nullable=True))
        batch_op.drop_column('can_geohysic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_geohysic', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('can_geophysic')

    # ### end Alembic commands ###
