"""Initial migration based on current database

Revision ID: b9498a06990c
Revises: 94b3cc1dc939
Create Date: 2024-10-08 14:13:23.520015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9498a06990c'
down_revision = '94b3cc1dc939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_users', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('can_users')

    # ### end Alembic commands ###
