"""new geophy coordinats

Revision ID: f0e2b7196218
Revises: 58aa5da2270e
Create Date: 2024-11-27 18:07:36.488934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0e2b7196218'
down_revision = '58aa5da2270e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geophysic_seismic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_latitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('first_longitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('second_latitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('second_longitude', sa.Float(), nullable=False))
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geophysic_seismic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('latitude', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('second_longitude')
        batch_op.drop_column('second_latitude')
        batch_op.drop_column('first_longitude')
        batch_op.drop_column('first_latitude')

    # ### end Alembic commands ###
