"""Set default values for boolean fields to False

Revision ID: fad975a3db37
Revises: 
Create Date: 2024-07-17 13:50:15.364716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad975a3db37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    with op.batch_alter_table('geophysical', schema=None) as batch_op:
        batch_op.drop_column('vs30_section')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geophysical', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vs30_section', sa.VARCHAR(), nullable=False))

    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('projects_name', sa.VARCHAR(), nullable=False),
    sa.Column('contract_number', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.DATE(), nullable=False),
    sa.Column('end_time', sa.DATE(), nullable=False),
    sa.Column('contractor', sa.VARCHAR(), nullable=False),
    sa.Column('proj_location', sa.VARCHAR(), nullable=False),
    sa.Column('proj_latitude', sa.FLOAT(), nullable=False),
    sa.Column('proj_longitude', sa.FLOAT(), nullable=False),
    sa.Column('geological_study', sa.BOOLEAN(), nullable=False),
    sa.Column('geophysical_study', sa.BOOLEAN(), nullable=False),
    sa.Column('hazard_study', sa.BOOLEAN(), nullable=False),
    sa.Column('geodetic_study', sa.BOOLEAN(), nullable=False),
    sa.Column('other_study', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
